# Generated by Django 4.2.2 on 2023-07-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='username',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
