# Generated by Django 4.2.2 on 2023-07-08 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0003_alter_data_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
